language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t hemakumark/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true hemakumark/docker-react yarn test